/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.6.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Binary = string;
export interface InstantiateMsg {
  oracle_key_type: string;
  oracle_pubkey: Binary;
}
export type ExecuteMsg = {
  send: {
    recipient: string;
  };
} | {
  oracle_data_update: {
    data: string;
    signature: Binary;
  };
} | {
  update_oracle: {
    new_key_type?: string | null;
    new_pubkey: Binary;
  };
};
export type QueryMsg = {
  get_oracle_data: {};
} | {
  get_oracle_pubkey: {};
} | {
  get_admin: {};
};
export type Addr = string;
export interface AdminResponse {
  admin: Addr;
}
export interface OracleDataResponse {
  data?: string | null;
}
export interface OraclePubkeyResponse {
  key_type: string;
  pubkey: Binary;
}